version: '3.7'

services:
  assignee-ms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assignee-ms
    ports:
      - "8081:8080"
    volumes:
      - ./target:/app/target
    networks:
      - backend-assignee
    environment:
      ASSIGNEE_MONGO_USERNAME: ${ASSIGNEE_MONGO_USERNAME}
      ASSIGNEE_MONGO_PASSWORD: ${ASSIGNEE_MONGO_PASSWORD}
      ASSIGNEE_MONGO_HOST: ${ASSIGNEE_MONGO_HOST}
      ASSIGNEE_MONGO_PORT: ${ASSIGNEE_MONGO_PORT}
      ASSIGNEE_MONGO_DB: ${ASSIGNEE_MONGO_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
  mongo-assignee:
    container_name: mongo-assignee
    image: mongo
    ## no se mapea los puertos ya que la bd unicamente sera accesible desde el ms
    volumes:
      - /mongo-data-assignee-ms:/data/db
    networks:
      - backend-assignee
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ASSIGNEE_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ASSIGNEE_MONGO_INITDB_ROOT_PASSWORD}
networks:
  backend-assignee:
    name: backend-assignee
    driver: bridge